- name: 'Configuring current system with standard tools'
  hosts: all
  connection: local
  become: yes
  become_user: root
  roles:
    - ngetchell.vscode
    - sansible.golang
    - andrewrothstein.kind
    - andrewrothstein.kubectl
    - geerlingguy.helm
  vars:
    user: debian
    vscode_extensions:
      - 2gua.rainbow-brackets
      - ms-python.python
      - golang.go      
  tasks:      
    - name: 'Installing VSCode extensions'
      become: yes
      become_user: '{{ user }}'
      shell: 'code --install-extension {{item}}'
      loop: '{{ vscode_extensions }}'
    - name: 'Add Golang bin to path'
      copy:
        src: path-go.sh
        dest: /etc/profile.d/path-go.sh
        mode: '0644'
